require("plugins")
require("theme")
require("loader")
--require("nvim-header").setup()
require("config.dap.dap-config")
require("config.lsp.lsp_config").setup()
require("config.lsp.lsp-installer")
require("config.lsp.cmp")
